name: DockerImageBuilder

on:
  push:
    tags:
     - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      
    - name: Print Tag
      run: echo ${{steps.tag.outputs.tag}}
    - name: GitHub Docker Action
      # You may pin to the exact commit or the version.
      # uses: matootie/github-docker@c1290d4f67c6fc0cdf84b2924d6dccf658129b3e
      uses: matootie/github-docker@v3.1.0
      with:
        # GitHub Repository Token to log in using.
        accessToken: ${{ secrets.TOKEN_GH }}
        # The desired name for the image. Defaults to current repository name.
        imageName: flutter-web
        # The desired tag for the image. Defaults to latest. Optionally accepts multiple tags separated by newline.
        tag: |
          ${{steps.tag.outputs.tag}}
        # Any additional build arguments to use when building the image, separated by newline.
        buildArgs: |
          flutter_version=${{steps.tag.outputs.tag}}
        # Whether or not to push to GitHub Container Registry instead of GitHub Package Registry.
        containerRegistry: true

